### ISSUE TITLE
Custom: My Spells - tooltip

### ISSUE THREAD

**Issue by Esstiven** [Bunny67/Details-WotLK#13]
This **error** showed up on the chat when trying to hover over any ability in the "Custom ->My Spell"

`Details!: error on custom display tooltip function: [string "		--config:..."]:109: attempt to perform arithmetic on field 'm_amt' (a nil value)`

![image](https://user-images.githubusercontent.com/50774648/84105768-4649c280-a9e7-11ea-95cf-cd3ccbd0e129.png)

**Comment by ajseward** [comment]
I fixed the default script so this wont happen to new users, but you will need to reimport the my spells custom display script.
https://pastebin.com/hs7Lp4eU paste this into Options -> Custom Displays -> Import  and then remove the old My Spells display
