### ISSUE TITLE
[Spell List][Ignore Spell] Judgement of Light healing

### ISSUE THREAD

**Issue by mrnuggets** [Bunny67/Details-WotLK#16]
Healing Meter still shows Judgement of Light healing despite having it ignored in the Spell List tab.

https://gyazo.com/983cd2a6f8a5948e1ccad2ecc0bb7df9
https://gyazo.com/db9e102c5b899c9cde3be530eb9fe931

I tested other spells as well, same result, so the 'ignore spell' thingy might not be working at all.

Cheers

**Comment by InflictWounds** [comment]
You can ignore spells by adding a code to "Auto Run Code" in details! options.
`Details.SpellsToIgnore[SpellID] = true`
You can find the ID in Spell List by searching your spell, in your case 20267. As such you can ignore Judgment of Light by adding a line with 
`Details.SpellsToIgnore[20267] = true`

**Comment by mrnuggets** [comment]
Doesn't work. Still counts the healing.

**Comment by mrnuggets** [comment]
Closing this issue cause i have the code needed to fix the issue, since Bunny doesn't like the two commits that fixes this issue.
