### ISSUE TITLE
Val'anyr absorb shield not getting priority before Power Word: Shield

### ISSUE THREAD

**Issue by Zidras** [Bunny67/Details-WotLK#22]
Protection of Ancient Kings (64413) is consumed before priest shield.
Stream evidence using details on light of dawn initial infest absorb: https://www.twitch.tv/videos/651947169?t=1h37m53s
And same fight using Skada, for comparison: https://www.twitch.tv/videos/654788921?t=1h24m28s

**Comment by ajseward** [comment]
As far as Trinity core goes, valnyr does not get special priority. https://github.com/Bunny67/Details-WotLK/pull/5

**Comment by Zidras** [comment]
Just tested on icecrown and you are correct. Apologize for not testing this properly be4hand
