### ISSUE TITLE
[Hunters] Snake Trap doesn't count towards hunter damage.

### ISSUE THREAD

**Issue by Esstiven** [Bunny67/Details-WotLK#24]
Currently Snake Trap is not shown. Details does not show this spell for Hunters.

**Comment by ajseward** [comment]
https://github.com/Bunny67/Details-WotLK/issues/10 probably related / same issue. 

The fix I did seems to only have fixed it while not in a group. I'll see if I can get a shaman or hunter friend to help soon.

**Comment by ajseward** [comment]
this was fixed in #36
