### ISSUE TITLE
[Encounter] Twin Val'kyr absorbs

### ISSUE THREAD

**Issue by InflictWounds** [Bunny67/Details-WotLK#26]
On twin val'kyrs if you run into an orb whilst having the same affinity on you, you absorb the damage, this is incorrectly counted towards players absorbs such as Disc shield and Val'anyr.

**Comment by InflictWounds** [comment]
Is still bugged, https://i.imgur.com/vZanvz3.png

**Comment by ajseward** [comment]
I'll check this out today.
