### ISSUE TITLE
[Suggestion] Add Parries

### ISSUE THREAD

**Issue by dominotrix** [Bunny67/Details-WotLK#31]
Would be really helpful to include parries the boss did and from which players so that we know who to yell at on Sindragosa :D

**Comment by ajseward** [comment]
![image](https://user-images.githubusercontent.com/16847730/86690827-20e7ae80-bfbd-11ea-887c-0e1f280617e5.png)
Are you sure these aren't being tracked?

**Comment by ArsumPB** [comment]
I think he meant a separate tab/category like damage or healing for boss parries, so we can see a parry "leaderboard" without having to check each melee individually and all their abilities

**Comment by ajseward** [comment]
That's what custom displays are for. 

I'll see if I can write one later

**Comment by ajseward** [comment]
Import this in Config -> Tools -> Custom Displays
![image](https://user-images.githubusercontent.com/16847730/88109822-020e1e00-cb60-11ea-9f4c-bac394383483.png)

```Tw1xpnooq8Vl8cTI0kUxrIhs)d9A2YbIKBLwDCPX1XT1lP2r2tyfV4p73y7KqljSWjHIAJJNz(n)Mz8mo9pstsJ1YkfLLUjnMub7LQ04jaF0nkPgoGIeS04CMMMgNOi0N0MSTeEbl3KraWUbIqjROGNBHqqoG6FtTgHTAqv8sinE0ODmWKb7zMSsIcvgykTDTwJgeviPKct2u5HneiaxuPb5HPsbq4cMc3zPqdebfT)At24XJnrJgLZOfKCwnUptkQyiMG0KPyagbT4csGueyFxI)tWWtaoGUmO(NjYbOSgRcPS0eTvQmzRTwqb7sUa)vs4k9aptVAbdcTYwX1WGzZtcxUkEDysYdlN83jZxpl82WfZho0KHihzY8p8TdCaE1s99fKxyQbOcerETFWTxOKvLnYg64K4v7BEQdoFzzn91G6Dv1vW0oL8Uc5FSDph)h(U2HLm1lb2OiFhdFVb3)j89bUwFAEmOx33MiDeWNi95rpJ8jOSUg284iGZt1RUWK5T9Fo)(WhE4hN)VMmRtUC47dIJ9oqQxDeiZUB2I5FgqCHUdK6vhbYKv3n9BFgqAZB(fhbXTlJJ)DiWWJjD20vlhtD9mR7KQ(a9FBw53RDNW)d0)0iT7bJ3E2TVq5I(z8f9tTl6JbDC8BgWCvyE(3TZp8DMbNYSJQdU8VViGZl4BnzcjY8debzNDYhxO5TtKStrqOED0xZik52tMj1097NlfDIKR7YvSPnXQsOi)p572Z0GN6inpA0wpw9xvhCtR0UwDK)1JjpHCrTB23qt0S0yGOWyYo2NtLI04LcCA(wcL94s8B9JHB4fC4L13BRF41laO4BQa3DnGuwa8Yp9vcn1dAZvd8oxeyJKxXI6DaMK38tgf3DWVy2Z220sLM1QL4zMGYLcRtwGEpPXU9mfByR)TIM2i66t)255wHujw4JosU9q1km3p4mxI4SG(oEJEAgdlrfAR61KycE75o8oaroMRHk9gIYxY6d9ZNz7hopOVUKVa0Vf7F6aUTP6la7j2wwwEh4DTY))W)R6jfst)Vd```
