### ISSUE TITLE
spell.lua and DF_COOLDOWN_UTILITY = 5

### ISSUE THREAD

**Issue by Shaterhand** [Bunny67/Details-WotLK#39]
Any ability that is defined with value 5 in the ability list in DF/spell.lua is not being tracked, for example is not being tracked by Event Tracker Plugin. But if you change the value to any other value than 5, it works.
![image](https://user-images.githubusercontent.com/56134900/87045284-621bd080-c200-11ea-980b-09fbca4d4109.png)
In the image above, aura mastery works and hammer of justice doesn't, but if you change the 5 to 1 for example, HoT will be tracked.

![image](https://user-images.githubusercontent.com/56134900/87045422-88da0700-c200-11ea-8e59-a74763efaad4.png)

**Comment by ajseward** [comment]
https://github.com/Bunny67/Details-WotLK/blob/2374b4728a7c88027d18c4e49313d68a7f98dcc9/Details/core/windows.lua#L6057-L6106 related bit of code for this
