### ISSUE TITLE
Details aura collection conflict with weakauras in raid group

### ISSUE THREAD

**Issue by FabioRNT** [Bunny67/Details-WotLK#63]
I noticed that my details were not collecting potion usage correctly. I went then on sandbox mode and disabled addon by addon until I found out that the aura collection was conflicting with Weakauras when I created a raid group, and it does not collect auras from everyone in the raid.

Here is an example:
Without weakauras enabled
![weakauras-details-issue](https://user-images.githubusercontent.com/19804284/111073232-baf0e680-84bc-11eb-85b7-c3c4ea76df42.png)

With weakauras enabled
![weakauras-details-issue-2](https://user-images.githubusercontent.com/19804284/111073244-ca702f80-84bc-11eb-8669-693a0064eb75.png)

**Comment by Szyler** [comment]
I am having the same issue.
