### ISSUE TITLE
Sirus. Ошибки lua в compat.lua

### ISSUE THREAD

**Issue by MrSago** [Bunny67/Details-WotLK#65]
Приветствую! Я понимаю что стандартный 3.3.5 отличается от кастомного Сируса, но можно это как-то пофиксить? Буду очень благодарен! По сути Details продолжает неплохо работать, но генерит бесконечные ошибки.
Включен был только этот аддон. Ругается на файл compat.lua. Ниже лог ошибки.
> Message: Interface\AddOns\Details\compat.lua:68: attempt to compare number with table
Time: 04/07/21 10:33:51
Count: 11990
Stack: Interface\AddOns\Details\compat.lua:68: in function <Interface\AddOns\Details\compat.lua:58>
Locals: self = TimerFrame {
 0 = <userdata>
}
elapsed = 0.010000000707805
total = 3
i = 1
ticker = <table> {
 _callback = 1
 _remainingIterations = <function> defined @Interface\FrameXML\ChatFrame.lua:4464
 _duration = <table> {
 }
 _delay = <table> {
 }
}
(*temporary) = <table> {
 _version = 2
 NewTimer = <function> defined @Interface\AddOns\Details\compat.lua:124
 After = <function> defined @Interface\AddOns\Details\compat.lua:116
 NewTicker = <function> defined @Interface\AddOns\Details\compat.lua:128
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with table"
waitTable = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
tremove = <function> defined =[C]:-1

**Comment by Barsoomx** [comment]
WeakAuras стоит?

**Comment by Barsoomx** [comment]
Если стоит - попробуй отключить и скажи есть ли ошибки - если нет - скинь свою папку аддонов, Bunny заниматься этим точно не будет, а я посмотрю где конфликт

**Comment by MrSago** [comment]
> WeakAuras стоит?

Проверял абсолютно без аддонов, удалял кэши, втф, делал проверку клиента, одна хурма.

**Comment by Barsoomx** [comment]
а без аддонов что если в игре ввести /dump C_Timer

**Comment by MrSago** [comment]
> а без аддонов что если в игре ввести /dump C_Timer

![image](https://user-images.githubusercontent.com/37180898/114245256-ca1e6380-9998-11eb-878a-63626a6d9034.png)

**Comment by Barsoomx** [comment]
Ну вообще можешь просто во всех файлах Details поменять C_Timer на C_Timer_Old, например, видимо в клиенте на сирусе реализовано как метод класса (C_Timer:After а не C_Timer.After)

**Comment by Bunny67** [comment]
https://gitlab.com/Bunny67/details
