### ISSUE TITLE
TinyThreat lua error

### ISSUE THREAD

**Issue by Zidras** [Bunny67/Details-WotLK#9]
```
Message: ...ace\AddOns\Details_TinyThreat\Details_TinyThreat.lua:406: bad argument #1 to '_unpack' (table expected, got nil)
Time: 06/07/20 00:01:55
Count: 153
Stack: [C]: ?
[C]: ?
...ace\AddOns\Details_TinyThreat\Details_TinyThreat.lua:406: in function <...ace\AddOns\Details_TinyThreat\Details_TinyThreat.lua:244>
...ace\AddOns\Details_TinyThreat\Details_TinyThreat.lua:489: in function `?'
...erface\AddOns\BLT\libs\AceTimer-3.0\AceTimer-3.0.lua:41: in function <...erface\AddOns\BLT\libs\AceTimer-3.0\AceTimer-3.0.lua:36>

Locals: 
```

**Comment by Bunny67** [comment]
Take a screenshot of the settings TinyThreat
![image](https://user-images.githubusercontent.com/5816685/83956257-a06e4a80-a864-11ea-961f-8783e2c5158d.png)

**Comment by ajseward** [comment]
this might have been fixed by https://github.com/Bunny67/Details-WotLK/commit/430af93b05eebaf9de714fcc972134d69b492499 unless you were already running an up to date version

**Comment by Zidras** [comment]
![image](https://user-images.githubusercontent.com/10605951/83958381-e9c09900-a868-11ea-894f-4652591108af.png)
But indeed my version is prior to that commit. I'll check later if I can replicate the issue and if not ill close it tomorrow. Ty
